
version: '3.3'
services:
  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    restart: always
    container_name: ${CONTAINER_NAME_PREFIX}telegraf
    hostname: telegraf
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    links:
      - influxdb
    networks:
      - default
      - nginx_proxy

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    restart: always
    container_name: ${CONTAINER_NAME_PREFIX}influxdb
    hostname: influxdb
    environment:
      - VIRTUAL_HOST=${INFLUXDB_HOST}
      - VIRTUAL_PORT=8086
      - LETSENCRYPT_HOST=${INFLUXDB_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./volumes/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb:/var/lib/influxdb:rw
    networks:
      - default
      - nginx_proxy

  chronograf:
    image: chronograf:${CHRONOGRAF_VERSION}
    restart: always
    container_name: ${CONTAINER_NAME_PREFIX}chronograf
    hostname: chronograf
    environment:
      - VIRTUAL_HOST=${CHRONOGRAF_HOST}
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=${CHRONOGRAF_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - KAPACITOR_URL=http://kapacitor:9092
      - KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER}
      - KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
    links:
      - influxdb
    networks:
      - default
      - nginx_proxy

  kapacitor:
    image: kapacitor:${KAPACITOR_VERSION}
    restart: always
    container_name: ${CONTAINER_NAME_PREFIX}kapacitor
    hostname: kapacitor
    environment:
      - VIRTUAL_HOST=${KAPACITOR_HOST}
      - VIRTUAL_PORT=9092
      - LETSENCRYPT_HOST=${KAPACITOR_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    links:
      - influxdb
    networks:
      - default
      - nginx_proxy

networks:
  nginx_proxy:
    external:
      name: nginxproxy_default
